library(arules)
data(Groceries)
summary(Groceries)
inspect(Groceries[1:5])
itemFrequency(Groceries[,1:3])
itemFrequencyPlot(Groceries, support=0.1)
itemFrequencyPlot(Groceries, topN = 20)
image(Groceries[1:5])
image(sample(Groceries,100))
apriori(Groceries)
groceryrules <- apriori(Groceries, parameter=list(support=0.006, confidence = 0.25, minlen=2))
groceryrules
summary(groceryrules)
inspect(groceryrules[1:3])
inspect(sort(groceryrules, by = "lift")[1:5])
berryrules <- subset(groceryrules, items %in% "berries")
inspect(berryrules)
write(groceryrules,  file = "groceryrules.csv")
groceryrules_df <- as(groceryrules, "data.frame")
str(groceryrules_df)