install.packages("tidyverse", dependencies=TRUE)
library(DBI)
library(plyr)
install.packages("arulesViz", dependencies = TRUE)
library(arulesViz)
library(DBI)
library(dbplyr)
install.packages("odbc", dependencies = TRUE)
library(odbc)
install.packages("RJDBC", dependencies = TRUE)
require(RJDBC)
install.packages("RODBC", dependencies = TRUE)
require(RODBC)
library(arules)
library(arulesViz)
bread_basket <- read.csv("C:\\Users\\Hariprasath\\Desktop\\R\\14\\bread basket.csv")
View(bread_basket)
bread_basket=as.data.frame(bread_basket)
head(bread_basket,10)
sum(is.na(bread_basket))
sorted <- bread_basket[order(bread_basket$Transaction),]
sorted$Transaction <- as.numeric(sorted$Transaction)
str(sorted)
itemList <- ddply(sorted, c("Transaction","date_time"), 
                  function(df1)
                    paste(df1$Item, collapse = ","))
itemList$Transaction <- NULL
itemList$date_time <- NULL
itemList$period_day <- NULL
itemList$weekday_weekend <- NULL
colnames (itemList) <- c("itemList")
write.csv(itemList, "itemList.csv", quote=FALSE, row.names=TRUE)
head(itemList, 10)
str(itemList)
transaksi = read.transactions("./itemList.csv", format="basket",sep=",",cols=1)
transaksi
basket_rules = apriori(transaksi, parameter = list(sup=0.01, minlen=3, conf=0.1, target="rules"))
print(length(basket_rules))
summary(basket_rules)
inspect(basket_rules)
plot(basket_rules, jitter=0)
itemFrequencyPlot(transaksi, topN=10)
plot(basket_rules, method="graph")
plot(basket_rules, method="paracoord")